### ISSUE TITLE
"SENTINEL1_GRD" band metadata is not properly enriched

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-python-client#277]
The band metadata for collection "SENTINEL1_GRD" is not properly enriched by the STAC metadata at https://collections.eurodatacube.com/stac/sentinel-1-grd.json.

This is because the order of the bands in "cube:dimensions"/"bands"/"values" is different from the order of bands in "summaries"/"raster:bands":

```json
{"values":["VV","VH","HH","HV"]}
```
as opposed to
```json
{
  "raster:bands":[
    {
      "name":"VV",
    },
    {
      "name":"VH",
    },
    {
      "name":"HV",
    },
    {
      "name":"HH",
    }
  ]
}
```

The [specification](https://github.com/stac-extensions/datacube#additional-dimension-object) says that "values" is "A set of all potential values" so that implies that it is unordered.

**Comment by m-mohr** [comment]
Actually, the values in STAC should be ordered. I guess this should be fixed in STAC.

**Comment by soxofaan** [comment]
Is there anything that should be fixed/adapted at the level of the python client?

**Comment by bossie** [comment]
No, apparently it's something that Sinergise should fix (but not quite yet because it will break our S1 collections: https://github.com/Open-EO/openeo-geopyspark-driver/issues/129).

**Comment by soxofaan** [comment]
I think this ticket should be re-opened because it's still an issue:

```python
import openeo
con = openeo.connect("openeo.vito.be")
datacube = con.load_collection('SENTINEL1_GRD')
```
triggers warning:
```
.../openeo/metadata.py:284: UserWarning: Band name mismatch: ['VV', 'VH', 'HH', 'HV'] != ['VV', 'VH', 'HV', 'HH']
  complain("Band name mismatch: {a} != {b}".format(a=cube_dimension_band_names, b=eo_band_names))
```

And practically it means that the client potentially will use wrong index when translating `cube.band("HH")` to a reduce_dimension callback like `array_element(data, index=3)`
​

**Comment by soxofaan** [comment]
Metadata issue must be fixed at back-end side.
But what we can do in the client is not supporting e.g. `cube.band("HH")`  if the band's  position is unclear

**Comment by bossie** [comment]
https://github.com/Open-EO/openeo-geopyspark-driver/issues/129 was fixed so I adapted layercatalog.json in order to align the band names and get rid of the warning.

**Comment by soxofaan** [comment]
Confirmed, I don't get the UserWarning  anymore when loading "SENTINEL1_GRD" on  openeo-dev.vito.be
